# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddusage < Formula
  desc "A tool that shows a breakdown of Datadog usages in a table."
  homepage "https://github.com/winebarrel/ddusage"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.1.0/ddusage_0.1.0_darwin_amd64.tar.gz"
      sha256 "e3d3e0dea1bde8f9015400912a5a99f62485fb1dd12646738ba012335c6d8ab4"

      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.1.0/ddusage_0.1.0_darwin_arm64.tar.gz"
      sha256 "aef6008167fe7eb0906f7c446e9f6387753b47344a16d9a5db705e0fd96d5d3c"

      def install
        bin.install 'ddusage'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.1.0/ddusage_0.1.0_linux_amd64.tar.gz"
      sha256 "bc5754f9158671adcd430f5c49c90f31a015f76c07a324ca3e1b8dcca4c00ea5"

      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.1.0/ddusage_0.1.0_linux_arm64.tar.gz"
      sha256 "f92b952fd7fb7a1e27367820657ed0c72ca8c0d007849caaca68c7af999f621e"

      def install
        bin.install 'ddusage'
      end
    end
  end
end
