# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddusage < Formula
  desc "A tool that shows a breakdown of Datadog usages in a table."
  homepage "https://github.com/winebarrel/ddusage"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.2/ddusage_0.2.2_darwin_amd64.tar.gz"
      sha256 "acfb9c9c3f0137d0682157846f5ca66d4d887a5ef7055d07d1cd31bf30514a3a"

      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.2/ddusage_0.2.2_darwin_arm64.tar.gz"
      sha256 "c607e7a1cc54b91ab0a6e4c44df9f59643fae4b2193426e55c95f08873277871"

      def install
        bin.install 'ddusage'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.2/ddusage_0.2.2_linux_amd64.tar.gz"
      sha256 "ac01b5d1283581309a07d0db0b91059815715a87354232b1ed6481bc917129d2"
      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.2/ddusage_0.2.2_linux_arm64.tar.gz"
      sha256 "e1adf3c0d0bd9ecffc006f19bef0253098c5f343e33659cb39b96e9a1580a3d7"
      def install
        bin.install 'ddusage'
      end
    end
  end
end
