# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddusage < Formula
  desc "A tool that shows a breakdown of Datadog usages in a table."
  homepage "https://github.com/winebarrel/ddusage"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.0/ddusage_0.2.0_darwin_arm64.tar.gz"
      sha256 "e225c3af23fc8313a5b8febbda27b46d3a6c24ab2433f867acff3674a76a56cf"

      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.0/ddusage_0.2.0_darwin_amd64.tar.gz"
      sha256 "162fc0b967d5b94e4f85694e33fc3b722ec5097f60b41e61cd9abee564bf7430"

      def install
        bin.install 'ddusage'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.0/ddusage_0.2.0_linux_arm64.tar.gz"
      sha256 "5c9cb831b8b0da807357625db7150e1563b9f3b61df9768473ae6bd684add820"

      def install
        bin.install 'ddusage'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddusage/releases/download/v0.2.0/ddusage_0.2.0_linux_amd64.tar.gz"
      sha256 "56a71988f27dcec638234985531b9e4fc1ab351a0c36202e865aa9ff95fa496e"

      def install
        bin.install 'ddusage'
      end
    end
  end
end
